# TP1 - Breno Lobato Vila Nova - 10/08/2026

## Criação da Base de Dados(Se necessário)
- ./data/tickets_suporte.csv
- ./data/planos_clientes.xlsx
- ./data/chatbot_triagem.json

In [1]:
from pathlib import Path
import shutil

In [2]:
DATA_FOLDER = "./data/"
SUPPORT_TICKETS_FILE_NAME = "tickets_suporte.csv"
CUSTOMER_PLANS_FILE_NAME = "planos_clientes.xlsx"
CHATBOT_TRIAGES_FILE_NAME = "chatbot_triagem.json"
SUPPORT_TICKETS_PATH = DATA_FOLDER + SUPPORT_TICKETS_FILE_NAME
CUSTOMER_PLANS_PATH = DATA_FOLDER + CUSTOMER_PLANS_FILE_NAME
CHATBOT_TRIAGES_PATH = DATA_FOLDER + CHATBOT_TRIAGES_FILE_NAME

In [3]:
def create_data():
    try:
        import data_scripts.create_data
        move_files_to_data_folder()
    except Exception as exception:
        raise RuntimeError("Erro ao criar a base de dados: " + str(exception))

def move_files_to_data_folder():
    support_tickets_file = Path(SUPPORT_TICKETS_FILE_NAME)
    customer_plans_file = Path(CUSTOMER_PLANS_FILE_NAME)
    chatbot_triages_file = Path(CHATBOT_TRIAGES_FILE_NAME)
    shutil.move(support_tickets_file, DATA_FOLDER)
    shutil.move(customer_plans_file, DATA_FOLDER)
    shutil.move(chatbot_triages_file, DATA_FOLDER)

In [4]:
# tickets_suporte.csv
support_tickets_path = Path(SUPPORT_TICKETS_PATH)
# planos_clientes.xlsx
customer_plans_path = Path(CUSTOMER_PLANS_PATH)
# chatbot_triagem.json
chatbot_triages_path = Path(CHATBOT_TRIAGES_PATH)

if (
    not support_tickets_path.is_file() 
    or not customer_plans_path.is_file() 
    or not chatbot_triages_path.is_file()
):
    create_data()

## Exercício 1
**Contexto**

Você foi contratado(a) como Engenheiro(a) de Dados Júnior na CloudDesk, uma empresa de software B2B que oferece uma plataforma de atendimento ao cliente. O time de Dados e IA recebeu um export bruto do sistema de tickets de suporte em formato CSV, contendo milhares de chamados abertos nos últimos seis meses. Antes de qualquer análise, seu líder técnico solicitou uma primeira inspeção do arquivo: quantas colunas existem, que tipos de dados o pandas inferiu automaticamente e quantas linhas estão presentes. Essa inspeção inicial é o primeiro passo de qualquer pipeline de análise e evita que decisões sejam tomadas sobre um dataset mal compreendido.

**Tarefa**

1. Carregue o arquivo tickets_suporte.csv com pandas.read_csv.
2. Inspecione o DataFrame resultante com shape, dtypes e info(), registrando o número de linhas, colunas e o tipo inferido para cada uma.
3. Escreva, em uma célula de markdown do notebook, três observações sobre o dataset com base nessa inspeção (ex.: colunas com tipo object que deveriam ser numéricas ou datas).

In [5]:
import pandas

In [6]:
# Loading support tickets dataframe
support_tickets_df = pandas.read_csv(SUPPORT_TICKETS_PATH)

In [7]:
print("Shape: ")
print(support_tickets_df.shape)

print("\nDtypes: ")
print(support_tickets_df.dtypes)

print("\nInfo: ")
print(support_tickets_df.dtypes)

Shape:
(4080, 9)

Dtypes:
ticket_id                 object
cliente_id                object
data_abertura             object
canal                     object
categoria                 object
prioridade                object
tempo_resposta_horas      object
tempo_resolucao_horas    float64
satisfacao_cliente       float64
dtype: object

Info:
ticket_id                 object
cliente_id                object
data_abertura             object
canal                     object
categoria                 object
prioridade                object
tempo_resposta_horas      object
tempo_resolucao_horas    float64
satisfacao_cliente       float64
dtype: object

### Resposta
Com base na saida do shape, dtypes e info do dataframe de tickets do suporte é possivel afirmar que:
1. A coluna `"tempo_resposta_hora"` está indicando `Object`, porém o seu nome faz a gente esperar um formato `float64`, assim como o `"tempo_resolucao_horas"`, ou pelo menos `int`.
2. A coluna `"data_abertura"` parece se referir a data, mas ele está com formato `Object` e não `datetime64`.
3. A coluna `"prioridade"`é um `Object` também, parece indicar se uma string, isso faz sentido para visualização, mas para analise talvez seja mais eficiente converter em int e quanto maior o número, maior a prioridade.

## Exercício 2
**Contexto**

O time financeiro da CloudDesk mantém uma planilha Excel própria com o valor do plano contratado por cada cliente, e o time de produto expõe os registros de interações do chatbot de triagem em formato JSON. Para calcular o impacto financeiro dos tickets, você precisa combinar essas três fontes de dados heterogêneas antes de qualquer análise. Cada fonte tem uma estrutura ligeiramente diferente, e seu primeiro trabalho é garantir que todas cheguem ao pandas como DataFrames utilizáveis.

**Tarefa**

1. Importe o arquivo planos_clientes.xlsx com pandas.read_excel.
2. Importe o arquivo chatbot_triagem.json com pandas.read_json.
3. Para cada uma das três fontes (CSV do Exercício 1, Excel, JSON), imprima as primeiras 5 linhas e o número de colunas, confirmando que a importação preservou os dados esperados.

### Tarefa 1. & 2.

In [8]:
customer_plans_df = pandas.read_excel(customer_plans_path)
chatbot_triages_df = pandas.read_json(chatbot_triages_path)

### Tarefa 3.

In [9]:
support_tickets_df.head(5)

,ticket_id,cliente_id,data_abertura,canal,categoria,prioridade,tempo_resposta_horas,tempo_resolucao_horas,satisfacao_cliente
0,TCK-00001,CLI-017,2026-01-05,chat,duvida_de_uso,media,"1,54",6.833510,4.0
1,TCK-00002,CLI-140,2026-01-05,email,cobranca,media,"2,05",6.664003,5.0
2,TCK-00003,CLI-118,2026-01-05,telefone,bug,baixa,"2,04",6.184528,4.0
3,TCK-00004,CLI-079,2026-01-05,email,bug,critica,"5,19",10.471215,3.0
4,TCK-00005,CLI-078,2026-01-05,chat,cobranca,baixa,"0,63",3.049426,4.0

In [10]:
customer_plans_df.head(5)

  cliente_id  valor_plano segmento
0    CLI-001           99   growth
1    CLI-002          199   growth
2    CLI-003           99  starter
3    CLI-004          599   growth
4    CLI-005          349   growth

In [11]:
chatbot_triages_df.head(5)

   ticket_id intencao_triagem  confianca_bot
0  TCK-00001       reclamacao           0.92
1  TCK-00005      solicitacao           0.90
2  TCK-00007       reclamacao           0.81
3  TCK-00010       reclamacao           0.74
4  TCK-00015      solicitacao           0.62

## Exercício 3
**Contexto**

Ao inspecionar o dataset de tickets, você percebeu que a coluna data_abertura foi lida como texto (object), a coluna prioridade deveria ser tratada como categórica para economizar memória e facilitar agrupamentos, e a coluna tempo_resposta_horas veio como texto por conter valores com vírgula decimal. Um pipeline de análise não pode avançar com tipos incorretos: cálculos estatísticos, ordenações temporais e agrupamentos dependem de cada coluna estar no tipo certo.

**Tarefa**

1. Utilize dtypes para listar o tipo atual de data_abertura, prioridade e tempo_resposta_horas.
2. Converta data_abertura para datetime64 e tempo_resposta_horas para float, ambos com astype (após tratar o separador decimal quando necessário).
3. Explique, em uma célula de markdown, por que manter prioridade como object em vez de convertê-la seria uma decisão ruim para um dataset com centenas de milhares de linhas.

### Tarefa 1.

In [12]:
support_tickets_df[["data_abertura", "prioridade", "tempo_resposta_horas"]].dtypes

data_abertura           object
prioridade              object
tempo_resposta_horas    object
dtype: object

### Tarefa 2.

In [13]:
# casting column "data_abertura" to datetime64
support_tickets_df["data_abertura"] = support_tickets_df["data_abertura"].astype("datetime64[ns]")

In [14]:
# casting column "tempo_resposta_horas" to float
support_tickets_df["tempo_resposta_horas"] = support_tickets_df["tempo_resposta_horas"]\
    .astype("str")\
    .str\
    .replace(",", ".")\
    .astype("float64")

In [15]:
# casting column "prioridade" to int
PRIORITY_DICT_TRANSLATOR = {
    "baixa": 1,
    "media": 2,
    "alta": 3,
    "critica": 4
}
support_tickets_df["prioridade"] = support_tickets_df["prioridade"].map(PRIORITY_DICT_TRANSLATOR)

In [16]:
support_tickets_df[["data_abertura", "tempo_resposta_horas", "prioridade"]].dtypes

data_abertura           datetime64[ns]
tempo_resposta_horas           float64
prioridade                       int64
dtype: object

### Tarefa 3.
Resposta: Manter a coluna `"prioridade"` como `Object` pode ser uma ser uma ideia ruim pois nesse formato ele irá ocupar mais espaço em memória, tornando seu modelo mais pesado, além de dificultar o modelo a entender que exister uma lógica naquele dado que indica o nível de urgência da ticket.

## Exercício 4

**Contexto**

Seu líder técnico pediu um recorte específico do dataset de tickets: apenas os chamados abertos pelo canal "chat" durante a segunda semana de dados, junto com as colunas ticket_id, categoria e tempo_resposta_horas. Esse tipo de recorte por posição e por rótulo é constante no dia a dia de um engenheiro de dados, seja para gerar relatórios pontuais, seja para depurar um subconjunto suspeito de registros.

**Tarefa**

1. Utilize loc para selecionar apenas as colunas ticket_id, categoria e tempo_resposta_horas de todo o dataset.
2. Utilize iloc para selecionar as linhas correspondentes às posições 500 a 800 (a segunda semana de dados, segundo a ordem de carregamento) desse subconjunto de colunas.
3. Compare em uma frase quando você usaria loc em vez de iloc em um pipeline real.

### Tarefa 1.

In [25]:
support_tickets_df_sliced = support_tickets_df.loc[:, ["ticket_id", "categoria", "tempo_resposta_horas"]]

### Tarefa 2.

In [18]:
support_tickets_df_sliced_in_range = support_tickets_df_sliced.iloc[500:801]

### Tarefa 3.

Resposta: O `iloc` eu usaria quando estivesse em usa situação que quisesse pegar as linhas do dataframe pelo index da posição delas, enquanto o `loc` eu usario quando quisesse pegar as linhas pelo label da index.

## Exercício 5

**Contexto**

A CloudDesk quer investigar se tickets de prioridade "alta" abertos pelo canal "email" estão demorando mais que o esperado para receber a primeira resposta. Antes de calcular qualquer métrica, você precisa isolar exatamente esse subconjunto de tickets usando condições compostas. Filtros booleanos mal escritos são uma fonte comum de erros silenciosos em pipelines de dados, por isso a legibilidade da condição importa tanto quanto o resultado.

**Tarefa**

1. Filtre o DataFrame de tickets para prioridade == "alta" e canal == "email" usando notação booleana composta com &.
2. Reescreva o mesmo filtro usando o método query().
3. Confirme que as duas abordagens retornam o mesmo número de linhas e explique, em uma frase, uma vantagem prática de query() sobre a notação booleana composta.

### Tarefa 1. Filtre o DataFrame de tickets para prioridade == "alta" e canal == "email" usando notação booleana composta com &.

In [19]:
PRIORITY_COLUMN = 'prioridade'
HIGH_PRIORITY_VALUE = PRIORITY_DICT_TRANSLATOR['alta'] # optimized value for 'alta' in integer
CHANNEL_COLUMN = 'canal'
EMAIL_CHANNEL_VALUE = 'email'

In [20]:
support_tickets_df_with_filters = support_tickets_df.loc[
    (support_tickets_df[PRIORITY_COLUMN] == HIGH_PRIORITY_VALUE)
     & (support_tickets_df[CHANNEL_COLUMN] == EMAIL_CHANNEL_VALUE)
]

In [21]:
support_tickets_df_with_filters.head(10)

,ticket_id,cliente_id,data_abertura,canal,categoria,prioridade,tempo_resposta_horas,tempo_resolucao_horas,satisfacao_cliente
8,TCK-00009,CLI-037,2026-01-05,email,cobranca,3,6.75,15.088345,5.0
35,TCK-00036,CLI-012,2026-01-06,email,cobranca,3,1.85,6.961171,5.0
38,TCK-00039,CLI-050,2026-01-06,email,bug,3,1.64,4.030364,5.0
45,TCK-00046,CLI-175,2026-01-07,email,bug,3,2.07,8.682418,5.0
62,TCK-00063,CLI-066,2026-01-07,email,duvida_de_uso,3,NaN,5.180166,5.0
70,TCK-00071,CLI-144,2026-01-07,email,duvida_de_uso,3,NaN,4.235048,5.0
81,TCK-00082,CLI-079,2026-01-08,email,duvida_de_uso,3,1.74,6.272907,5.0
83,TCK-00084,CLI-150,2026-01-08,email,duvida_de_uso,3,9.21,18.679381,3.0
125,TCK-00126,CLI-102,2026-01-10,email,duvida_de_uso,3,4.52,11.503741,4.0
142,TCK-00143,CLI-050,2026-01-11,email,bug,3,5.48,12.813458,5.0

### Tarefa 2. Reescreva o mesmo filtro usando o método query().

In [22]:
support_tickets_df_with_filters_with_query = support_tickets_df.query(
    "{} == {} & {} == '{}'".format(
        PRIORITY_COLUMN, HIGH_PRIORITY_VALUE,
        CHANNEL_COLUMN, EMAIL_CHANNEL_VALUE
    )
)

In [23]:
support_tickets_df_with_filters_with_query.head(10)

,ticket_id,cliente_id,data_abertura,canal,categoria,prioridade,tempo_resposta_horas,tempo_resolucao_horas,satisfacao_cliente
8,TCK-00009,CLI-037,2026-01-05,email,cobranca,3,6.75,15.088345,5.0
35,TCK-00036,CLI-012,2026-01-06,email,cobranca,3,1.85,6.961171,5.0
38,TCK-00039,CLI-050,2026-01-06,email,bug,3,1.64,4.030364,5.0
45,TCK-00046,CLI-175,2026-01-07,email,bug,3,2.07,8.682418,5.0
62,TCK-00063,CLI-066,2026-01-07,email,duvida_de_uso,3,NaN,5.180166,5.0
70,TCK-00071,CLI-144,2026-01-07,email,duvida_de_uso,3,NaN,4.235048,5.0
81,TCK-00082,CLI-079,2026-01-08,email,duvida_de_uso,3,1.74,6.272907,5.0
83,TCK-00084,CLI-150,2026-01-08,email,duvida_de_uso,3,9.21,18.679381,3.0
125,TCK-00126,CLI-102,2026-01-10,email,duvida_de_uso,3,4.52,11.503741,4.0
142,TCK-00143,CLI-050,2026-01-11,email,bug,3,5.48,12.813458,5.0

### Tarefa 3. Confirme que as duas abordagens retornam o mesmo número de linhas e explique, em uma frase, uma vantagem prática de query() sobre a notação booleana composta.

In [24]:
print("Comparando resultados:")

first_way_line_count = len(support_tickets_df_with_filters)
first_way_first_ticket_ids = set(support_tickets_df_with_filters['ticket_id'].head(6))
first_way_last_ticket_ids = set(support_tickets_df_with_filters['ticket_id'].tail(6))
print("- Dataframe Notação Booleana Composta:")
print("     Número de linhas: {}".format(first_way_line_count))
print("     Primeiros 6 ticket_ids: {}".format(first_way_first_ticket_ids))
print("     Últimos 6 ticket_ids: {}".format(first_way_last_ticket_ids))

query_way_line_count = len(support_tickets_df_with_filters_with_query)
query_way_first_ticket_ids = set(support_tickets_df_with_filters_with_query['ticket_id'].head(6))
query_way_last_ticket_ids = set(support_tickets_df_with_filters_with_query['ticket_id'].tail(6))
print("- Dataframe com query:")
print("     Número de linhas: {}".format(query_way_line_count))
print("     Primeiros 6 ticket_ids: {}".format(query_way_first_ticket_ids))
print("     Últimos 6 ticket_ids: {}".format(query_way_last_ticket_ids))

is_equal_line = "OK" if first_way_line_count == query_way_line_count else "DIFERENTE"
is_equal_first_ticket_ids = "OK" if first_way_first_ticket_ids == query_way_first_ticket_ids else "DIFERENTE"
is_equal_last_ticket_ids = "OK" if first_way_last_ticket_ids == query_way_last_ticket_ids else "DIFERENTE"

first_way_all_ticket_ids = set(support_tickets_df_with_filters['ticket_id'])
query_way_all_ticket_ids = set(support_tickets_df_with_filters_with_query['ticket_id'])
is_all_ticket_ids_equal = "OK" if first_way_all_ticket_ids == query_way_all_ticket_ids else "DIFERENTE"

print("Comparando fica:")
print("- Número de linhas: {}".format(is_equal_line))
print("- Primeiros 6 ticket_ids: {}".format(is_equal_line))
print("- Últimos 6 ticket_ids: {}".format(is_equal_line))
print("- Conjunto inteiro de ticket_ids: {}".format(is_all_ticket_ids_equal))

Comparando resultados:
- Dataframe Notação Booleana Composta:
     Número de linhas: 494
     Primeiros 6 ticket_ids: {'TCK-00036', 'TCK-00071', 'TCK-00063', 'TCK-00046', 'TCK-00039', 'TCK-00009'}
     Últimos 6 ticket_ids: {'TCK-01583', 'TCK-00706', 'TCK-00606', 'TCK-00009', 'TCK-00315', 'TCK-03380'}
- Dataframe com query:
     Número de linhas: 494
     Primeiros 6 ticket_ids: {'TCK-00036', 'TCK-00071', 'TCK-00063', 'TCK-00046', 'TCK-00039', 'TCK-00009'}
     Últimos 6 ticket_ids: {'TCK-01583', 'TCK-00706', 'TCK-00606', 'TCK-00009', 'TCK-00315', 'TCK-03380'}
Comparando fica:
- Número de linhas: OK
- Primeiros 6 ticket_ids: OK
- Últimos 6 ticket_ids: OK
- Conjunto inteiro de ticket_ids: OK

Resposta: O uso do metodo `query` possui uma eficiencia melhor que a `Notação Booleana Composta` em determinados cenários com grandes volumes, pois como o metodo `query` recebe a busca completa, ele pode otimizar ela em alguns cenarios, enquanto a notação `Notação Booleana Composta` não tem isso.

## Exercício 6

**Contexto**

O export bruto de tickets tem lacunas: cerca de 8% dos registros não têm tempo_resposta_horas preenchido (tickets ainda em aberto no momento do export) e alguns registros de satisfacao_cliente estão vazios porque o cliente não respondeu à pesquisa pós-atendimento. Ignorar valores ausentes sem critério pode enviesar qualquer estatística calculada depois. Você precisa decidir, para cada coluna, se o tratamento correto é preencher ou remover.

**Tarefa**

1. Identifique quantos valores ausentes existem em cada coluna do dataset de tickets.
2. Trate tempo_resposta_horas ausente com uma estratégia de preenchimento justificada (por exemplo, mediana por categoria) usando fillna.
3. Remova, com dropna, os registros em que ticket_id esteja ausente (chave primária não pode faltar).

## Exercício 7

**Contexto**

Durante a inspeção, você percebeu que o sistema de tickets registrou alguns chamados em duplicidade, provavelmente por reenvios automáticos do formulário de abertura. Manter duplicatas infla artificialmente contagens e médias, distorcendo qualquer relatório gerado a partir desse dataset.

**Tarefa**

Identifique quantas linhas duplicadas existem no dataset de tickets, considerando ticket_id como identificador de duplicidade.
Remova as duplicatas com drop_duplicates, mantendo o primeiro registro de cada ticket_id.
Reporte, em uma célula de markdown, quantas linhas foram removidas e o percentual que isso representa do dataset original.

## Exercício 8
**Contexto**

Agora que os tickets estão limpos e tipados, você precisa consolidar essa base com as duas outras fontes trabalhadas no Exercício 2: o valor do plano de cada cliente (Excel) e os registros de triagem do chatbot (JSON). O objetivo final é um único DataFrame consolidado, pronto para ser usado nas próximas etapas da disciplina.

**Tarefa**

1. Combine o DataFrame de tickets com o DataFrame de planos de clientes usando pd.merge, unindo pelo identificador de cliente comum às duas fontes.
2. Combine o resultado com os registros de triagem do chatbot usando pd.concat, quando aplicável ao mesmo esquema de colunas, ou pd.merge quando as chaves permitirem.
3. Confirme o número final de linhas e colunas do DataFrame consolidado.

## Exercício 9

**Contexto**

Com a base consolidada, seu líder técnico pediu um primeiro resumo agregado antes da reunião semanal: o tempo médio de resposta e o total de tickets por categoria de problema (ex.: "cobrança", "bug", "dúvida de uso"). Esse tipo de agregação por categoria é a base de qualquer relatório operacional de suporte.

**Tarefa**

1. Agrupe o DataFrame consolidado por categoria usando groupby.
2. Calcule, para cada grupo, a média de tempo_resposta_horas e a contagem de tickets.
3. Ordene o resultado da categoria com maior tempo médio de resposta para a menor e aponte, em uma frase, qual categoria merece atenção prioritária do time de suporte.