# TP2 - Breno Lobato Vila Nova - 24/08/2026

## Recriando dataframes TP1

### Criação da Base de Dados(Se necessário)

- ./data/tickets_suporte.csv
- ./data/planos_clientes.xlsx
- ./data/chatbot_triagem.json

In [1]:
from pathlib import Path
import shutil

In [2]:
DATA_FOLDER = "./data/"
SUPPORT_TICKETS_FILE_NAME = "tickets_suporte.csv"
CUSTOMER_PLANS_FILE_NAME = "planos_clientes.xlsx"
CHATBOT_TRIAGES_FILE_NAME = "chatbot_triagem.json"
SUPPORT_TICKETS_PATH = DATA_FOLDER + SUPPORT_TICKETS_FILE_NAME
CUSTOMER_PLANS_PATH = DATA_FOLDER + CUSTOMER_PLANS_FILE_NAME
CHATBOT_TRIAGES_PATH = DATA_FOLDER + CHATBOT_TRIAGES_FILE_NAME

In [3]:
def create_data():
    try:
        import data_scripts.create_data
        move_files_to_data_folder()
    except Exception as exception:
        raise RuntimeError("Erro ao criar a base de dados: " + str(exception))

def move_files_to_data_folder():
    support_tickets_file = Path(SUPPORT_TICKETS_FILE_NAME)
    customer_plans_file = Path(CUSTOMER_PLANS_FILE_NAME)
    chatbot_triages_file = Path(CHATBOT_TRIAGES_FILE_NAME)
    data_folder_path = Path(DATA_FOLDER)
    data_folder_path.mkdir(exist_ok=True)
    shutil.move(support_tickets_file, DATA_FOLDER)
    shutil.move(customer_plans_file, DATA_FOLDER)
    shutil.move(chatbot_triages_file, DATA_FOLDER, )

# tickets_suporte.csv
support_tickets_path = Path(SUPPORT_TICKETS_PATH)
# planos_clientes.xlsx
customer_plans_path = Path(CUSTOMER_PLANS_PATH)
# chatbot_triagem.json
chatbot_triages_path = Path(CHATBOT_TRIAGES_PATH)

if (
    not support_tickets_path.is_file() 
    or not customer_plans_path.is_file() 
    or not chatbot_triages_path.is_file()
):
    create_data()

### TP1 - Exercício 1

In [4]:
import pandas

In [5]:
# Loading support tickets dataframe
support_tickets_df = pandas.read_csv(SUPPORT_TICKETS_PATH)

In [6]:
print("Shape: ")
print(support_tickets_df.shape)

print("\nDtypes: ")
print(support_tickets_df.dtypes)

print("\nInfo: ")
print(support_tickets_df.dtypes)

Shape:
(4080, 9)

Dtypes:
ticket_id                 object
cliente_id                object
data_abertura             object
canal                     object
categoria                 object
prioridade                object
tempo_resposta_horas      object
tempo_resolucao_horas    float64
satisfacao_cliente       float64
dtype: object

Info:
ticket_id                 object
cliente_id                object
data_abertura             object
canal                     object
categoria                 object
prioridade                object
tempo_resposta_horas      object
tempo_resolucao_horas    float64
satisfacao_cliente       float64
dtype: object

### TP1 - Exercício 2

In [7]:
customer_plans_df = pandas.read_excel(customer_plans_path)
chatbot_triages_df = pandas.read_json(chatbot_triages_path)

In [8]:
support_tickets_df.head(5)

,ticket_id,cliente_id,data_abertura,canal,categoria,prioridade,tempo_resposta_horas,tempo_resolucao_horas,satisfacao_cliente
0,TCK-00001,CLI-017,2026-01-05,chat,duvida_de_uso,media,"1,54",6.833510,4.0
1,TCK-00002,CLI-140,2026-01-05,email,cobranca,media,"2,05",6.664003,5.0
2,TCK-00003,CLI-118,2026-01-05,telefone,bug,baixa,"2,04",6.184528,4.0
3,TCK-00004,CLI-079,2026-01-05,email,bug,critica,"5,19",10.471215,3.0
4,TCK-00005,CLI-078,2026-01-05,chat,cobranca,baixa,"0,63",3.049426,4.0

In [9]:
customer_plans_df.head(5)

  cliente_id  valor_plano segmento
0    CLI-001           99   growth
1    CLI-002          199   growth
2    CLI-003           99  starter
3    CLI-004          599   growth
4    CLI-005          349   growth

In [10]:
chatbot_triages_df.head(5)

   ticket_id intencao_triagem  confianca_bot
0  TCK-00001       reclamacao           0.92
1  TCK-00005      solicitacao           0.90
2  TCK-00007       reclamacao           0.81
3  TCK-00010       reclamacao           0.74
4  TCK-00015      solicitacao           0.62

### TP1 - Exercício 3

In [11]:
support_tickets_df[["data_abertura", "prioridade", "tempo_resposta_horas"]].dtypes

data_abertura           object
prioridade              object
tempo_resposta_horas    object
dtype: object

In [12]:
# casting column "data_abertura" to datetime64
support_tickets_df["data_abertura"] = support_tickets_df["data_abertura"].astype("datetime64[ns]")

In [13]:
# casting column "tempo_resposta_horas" to float
support_tickets_df["tempo_resposta_horas"] = support_tickets_df["tempo_resposta_horas"]\
    .astype("str")\
    .str\
    .replace(",", ".")\
    .astype("float64")

In [14]:
# casting column "prioridade" to int
PRIORITY_DICT_TRANSLATOR = {
    "baixa": 1,
    "media": 2,
    "alta": 3,
    "critica": 4
}
support_tickets_df["prioridade"] = support_tickets_df["prioridade"].map(PRIORITY_DICT_TRANSLATOR)

In [15]:
support_tickets_df[["data_abertura", "tempo_resposta_horas", "prioridade"]].dtypes

data_abertura           datetime64[ns]
tempo_resposta_horas           float64
prioridade                       int64
dtype: object

### TP1 - Exercício 4

In [16]:
support_tickets_df_sliced = support_tickets_df.loc[:, ["ticket_id", "categoria", "tempo_resposta_horas"]]

In [17]:
support_tickets_df_sliced_in_range = support_tickets_df_sliced.iloc[500:801]

### TP1 - Exercício 5

In [18]:
PRIORITY_COLUMN = 'prioridade'
HIGH_PRIORITY_VALUE = PRIORITY_DICT_TRANSLATOR['alta'] # optimized value for 'alta' in integer
CHANNEL_COLUMN = 'canal'
EMAIL_CHANNEL_VALUE = 'email'

In [19]:
support_tickets_df_with_filters = support_tickets_df.loc[
    (support_tickets_df[PRIORITY_COLUMN] == HIGH_PRIORITY_VALUE)
     & (support_tickets_df[CHANNEL_COLUMN] == EMAIL_CHANNEL_VALUE)
]

In [20]:
support_tickets_df_with_filters.head(10)

,ticket_id,cliente_id,data_abertura,canal,categoria,prioridade,tempo_resposta_horas,tempo_resolucao_horas,satisfacao_cliente
8,TCK-00009,CLI-037,2026-01-05,email,cobranca,3,6.75,15.088345,5.0
35,TCK-00036,CLI-012,2026-01-06,email,cobranca,3,1.85,6.961171,5.0
38,TCK-00039,CLI-050,2026-01-06,email,bug,3,1.64,4.030364,5.0
45,TCK-00046,CLI-175,2026-01-07,email,bug,3,2.07,8.682418,5.0
62,TCK-00063,CLI-066,2026-01-07,email,duvida_de_uso,3,NaN,5.180166,5.0
70,TCK-00071,CLI-144,2026-01-07,email,duvida_de_uso,3,NaN,4.235048,5.0
81,TCK-00082,CLI-079,2026-01-08,email,duvida_de_uso,3,1.74,6.272907,5.0
83,TCK-00084,CLI-150,2026-01-08,email,duvida_de_uso,3,9.21,18.679381,3.0
125,TCK-00126,CLI-102,2026-01-10,email,duvida_de_uso,3,4.52,11.503741,4.0
142,TCK-00143,CLI-050,2026-01-11,email,bug,3,5.48,12.813458,5.0

In [21]:
support_tickets_df_with_filters_with_query = support_tickets_df.query(
    "{} == {} & {} == '{}'".format(
        PRIORITY_COLUMN, HIGH_PRIORITY_VALUE,
        CHANNEL_COLUMN, EMAIL_CHANNEL_VALUE
    )
)

In [22]:
support_tickets_df_with_filters_with_query.head(10)

,ticket_id,cliente_id,data_abertura,canal,categoria,prioridade,tempo_resposta_horas,tempo_resolucao_horas,satisfacao_cliente
8,TCK-00009,CLI-037,2026-01-05,email,cobranca,3,6.75,15.088345,5.0
35,TCK-00036,CLI-012,2026-01-06,email,cobranca,3,1.85,6.961171,5.0
38,TCK-00039,CLI-050,2026-01-06,email,bug,3,1.64,4.030364,5.0
45,TCK-00046,CLI-175,2026-01-07,email,bug,3,2.07,8.682418,5.0
62,TCK-00063,CLI-066,2026-01-07,email,duvida_de_uso,3,NaN,5.180166,5.0
70,TCK-00071,CLI-144,2026-01-07,email,duvida_de_uso,3,NaN,4.235048,5.0
81,TCK-00082,CLI-079,2026-01-08,email,duvida_de_uso,3,1.74,6.272907,5.0
83,TCK-00084,CLI-150,2026-01-08,email,duvida_de_uso,3,9.21,18.679381,3.0
125,TCK-00126,CLI-102,2026-01-10,email,duvida_de_uso,3,4.52,11.503741,4.0
142,TCK-00143,CLI-050,2026-01-11,email,bug,3,5.48,12.813458,5.0

In [23]:
print("Comparando resultados:")

first_way_line_count = len(support_tickets_df_with_filters)
first_way_first_ticket_ids = set(support_tickets_df_with_filters['ticket_id'].head(6))
first_way_last_ticket_ids = set(support_tickets_df_with_filters['ticket_id'].tail(6))
print("- Dataframe Notação Booleana Composta:")
print("     Número de linhas: {}".format(first_way_line_count))
print("     Primeiros 6 ticket_ids: {}".format(first_way_first_ticket_ids))
print("     Últimos 6 ticket_ids: {}".format(first_way_last_ticket_ids))

query_way_line_count = len(support_tickets_df_with_filters_with_query)
query_way_first_ticket_ids = set(support_tickets_df_with_filters_with_query['ticket_id'].head(6))
query_way_last_ticket_ids = set(support_tickets_df_with_filters_with_query['ticket_id'].tail(6))
print("- Dataframe com query:")
print("     Número de linhas: {}".format(query_way_line_count))
print("     Primeiros 6 ticket_ids: {}".format(query_way_first_ticket_ids))
print("     Últimos 6 ticket_ids: {}".format(query_way_last_ticket_ids))

is_equal_line = "OK" if first_way_line_count == query_way_line_count else "DIFERENTE"
is_equal_first_ticket_ids = "OK" if first_way_first_ticket_ids == query_way_first_ticket_ids else "DIFERENTE"
is_equal_last_ticket_ids = "OK" if first_way_last_ticket_ids == query_way_last_ticket_ids else "DIFERENTE"

first_way_all_ticket_ids = set(support_tickets_df_with_filters['ticket_id'])
query_way_all_ticket_ids = set(support_tickets_df_with_filters_with_query['ticket_id'])
is_all_ticket_ids_equal = "OK" if first_way_all_ticket_ids == query_way_all_ticket_ids else "DIFERENTE"

print("Comparando fica:")
print("- Número de linhas: {}".format(is_equal_line))
print("- Primeiros 6 ticket_ids: {}".format(is_equal_line))
print("- Últimos 6 ticket_ids: {}".format(is_equal_line))
print("- Conjunto inteiro de ticket_ids: {}".format(is_all_ticket_ids_equal))

Comparando resultados:
- Dataframe Notação Booleana Composta:
     Número de linhas: 494
     Primeiros 6 ticket_ids: {'TCK-00009', 'TCK-00036', 'TCK-00071', 'TCK-00039', 'TCK-00046', 'TCK-00063'}
     Últimos 6 ticket_ids: {'TCK-00606', 'TCK-00009', 'TCK-00706', 'TCK-03380', 'TCK-00315', 'TCK-01583'}
- Dataframe com query:
     Número de linhas: 494
     Primeiros 6 ticket_ids: {'TCK-00009', 'TCK-00036', 'TCK-00071', 'TCK-00039', 'TCK-00046', 'TCK-00063'}
     Últimos 6 ticket_ids: {'TCK-00606', 'TCK-00009', 'TCK-00706', 'TCK-03380', 'TCK-00315', 'TCK-01583'}
Comparando fica:
- Número de linhas: OK
- Primeiros 6 ticket_ids: OK
- Últimos 6 ticket_ids: OK
- Conjunto inteiro de ticket_ids: OK

### TP1 - Exercício 6

In [24]:
print("- Linhas com valores ausentes para cada coluna: ")
print(support_tickets_df.isnull().sum())

- Linhas com valores ausentes para cada coluna:
ticket_id                  0
cliente_id                 0
data_abertura              0
canal                      0
categoria                  0
prioridade                 0
tempo_resposta_horas     329
tempo_resolucao_horas      0
satisfacao_cliente       407
dtype: int64

In [25]:
RESPONSE_TIME_COLUMN = 'tempo_resposta_horas'

In [26]:
average_response_time = support_tickets_df[RESPONSE_TIME_COLUMN].mean()

support_tickets_df[RESPONSE_TIME_COLUMN] = support_tickets_df[RESPONSE_TIME_COLUMN].fillna(average_response_time)

In [27]:
print("Novos vales ausentes de tempo_resposta_horas: {}".format(support_tickets_df[RESPONSE_TIME_COLUMN].isna().sum()))

Novos vales ausentes de tempo_resposta_horas: 0

In [28]:
TICKET_ID_COLUMN = 'ticket_id'

In [29]:
support_tickets_df = support_tickets_df.dropna(subset=[TICKET_ID_COLUMN])

In [30]:
support_tickets_df.isna().sum()

ticket_id                  0
cliente_id                 0
data_abertura              0
canal                      0
categoria                  0
prioridade                 0
tempo_resposta_horas       0
tempo_resolucao_horas      0
satisfacao_cliente       407
dtype: int64

### TP1 - Exercício 7

In [31]:
duplicated_ticket_ids_count = support_tickets_df[TICKET_ID_COLUMN].duplicated().sum()

print("A coluna 'ticket_id' possui {} ids duplicados.".format(duplicated_ticket_ids_count))

A coluna 'ticket_id' possui 80 ids duplicados.

In [32]:
# snapshot for future metrics
support_tickets_df_original = support_tickets_df.copy()

# drop of duplicates
support_tickets_df = support_tickets_df.drop_duplicates(subset=[TICKET_ID_COLUMN])

In [33]:
original_lines_count = len(support_tickets_df_original)
removed_lines_count = original_lines_count - len(support_tickets_df)

represented_porcentage = removed_lines_count / original_lines_count
represented_porcentage_displayable = represented_porcentage * 100
print("Número de linhas removidas: {}".format(removed_lines_count))
print("Tamanho que representava do dataset: {}%".format(represented_porcentage_displayable))

Número de linhas removidas: 80
Tamanho que representava do dataset: 1.9607843137254901%

### TP1 - Exercício 8

In [34]:
CUSTOMER_ID_COLUMN = 'cliente_id'

In [35]:
# Merging support tickets and customer plans
merged_dfs = support_tickets_df.merge(customer_plans_df, on=[CUSTOMER_ID_COLUMN], validate='many_to_one')

In [36]:
support_tickets_column_names = tuple(support_tickets_df.columns)
print("Colunas de tickets do suporte({}): ".format(len(support_tickets_column_names)))
for column in support_tickets_column_names: 
    print('- ' + column)

customers_plans_column_names = tuple(customer_plans_df.columns)
print("\nColunas de planos clientes({}): ".format(len(customers_plans_column_names)))
for column in customers_plans_column_names: 
    print('- ' + column)

merged_dfs_column_names = tuple(merged_dfs.columns)
print("\nColunas dos datasets mergeados({}): ".format(len(merged_dfs_column_names)))
for column in merged_dfs_column_names:
    print('- ' + column)

Colunas de tickets do suporte(9):
- ticket_id
- cliente_id
- data_abertura
- canal
- categoria
- prioridade
- tempo_resposta_horas
- tempo_resolucao_horas
- satisfacao_cliente

Colunas de planos clientes(3):
- cliente_id
- valor_plano
- segmento

Colunas dos datasets mergeados(11):
- ticket_id
- cliente_id
- data_abertura
- canal
- categoria
- prioridade
- tempo_resposta_horas
- tempo_resolucao_horas
- satisfacao_cliente
- valor_plano
- segmento

In [37]:
# left merge with 'ticket_id'
merged_dfs = merged_dfs.merge(chatbot_triages_df, how='left', on=[TICKET_ID_COLUMN])
len(merged_dfs)

4000

In [38]:
# concat remainder chatbot triages
not_merged_ticket_ids = set(chatbot_triages_df[TICKET_ID_COLUMN]) - set(merged_dfs[TICKET_ID_COLUMN])
remainder_triages = chatbot_triages_df[chatbot_triages_df[TICKET_ID_COLUMN] == not_merged_ticket_ids]
merged_dfs = pandas.concat([merged_dfs, remainder_triages])

In [39]:
all_column_names = set(merged_dfs.columns)
print("Colunas do dataframe final: ")
for column in all_column_names:
    print('    - ' + column)

print("Número de colunas: {}".format(len(all_column_names)))
print("Número de linhas: {}".format(len(merged_dfs)))

Colunas do dataframe final:
    - tempo_resposta_horas
    - confianca_bot
    - cliente_id
    - valor_plano
    - canal
    - segmento
    - intencao_triagem
    - ticket_id
    - categoria
    - prioridade
    - tempo_resolucao_horas
    - satisfacao_cliente
    - data_abertura
Número de colunas: 13
Número de linhas: 4000

### TP1 - Exercício 9

In [40]:
CATEGORY_COLUMN = 'categoria'

In [41]:
merged_dfs_by_group = merged_dfs.groupby(CATEGORY_COLUMN)

In [42]:
# Average by category
response_time_average_by_category = merged_dfs_by_group[RESPONSE_TIME_COLUMN].mean()

print("Tempo de resposta médio de cada categoria:")
print(response_time_average_by_category)

Tempo de resposta médio de cada categoria:
categoria
bug              3.801587
cobranca         3.981730
duvida_de_uso    3.782541
elogio           4.091509
Name: tempo_resposta_horas, dtype: float64

In [43]:
# tickets count by category
print("Quantidade de tickets por categori:")
print(merged_dfs_by_group[TICKET_ID_COLUMN].count())

Quantidade de tickets por categori:
categoria
bug              1387
cobranca         1028
duvida_de_uso    1192
elogio            393
Name: ticket_id, dtype: int64

In [44]:
print("Tempo de resposta médio de cada categoria ordenada: ")
response_time_average_by_category.sort_values(ascending=False)

Tempo de resposta médio de cada categoria ordenada:

categoria
elogio           4.091509
cobranca         3.981730
bug              3.801587
duvida_de_uso    3.782541
Name: tempo_resposta_horas, dtype: float64

## Exercício 1

In [46]:
print("hello")

hello